/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {};

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    GlobalSetting: typeof import('./src/components/global-setting/index.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TinyAvatar: typeof import('@opentiny/vue')['Avatar']
    TinyBadge: typeof import('@opentiny/vue')['Badge']
    TinyBreadcrumb: typeof import('@opentiny/vue')['Breadcrumb']
    TinyBreadcrumbItem: typeof import('@opentiny/vue')['BreadcrumbItem']
    TinyButton: typeof import('@opentiny/vue')['Button']
    TinyCard: typeof import('@opentiny/vue')['Card']
    TinyChart: typeof import('@opentiny/vue')['Chart']
    TinyCheckbox: typeof import('@opentiny/vue')['Checkbox']
    TinyContainer: typeof import('@opentiny/vue')['Container']
    TinyDatePicker: typeof import('@opentiny/vue')['DatePicker']
    TinyDropdown: typeof import('@opentiny/vue')['Dropdown']
    TinyForm: typeof import('@opentiny/vue')['Form']
    TinyFormItem: typeof import('@opentiny/vue')['FormItem']
    TinyInput: typeof import('@opentiny/vue')['Input']
    TinyLayout: typeof import('@opentiny/vue')['Layout']
    TinyLayoutAside: typeof import('@opentiny/vue')['LayoutAside']
    TinyLayoutMain: typeof import('@opentiny/vue')['LayoutMain']
    TinyMenu: typeof import('@opentiny/vue')['Menu']
    TinyMenuItem: typeof import('@opentiny/vue')['MenuItem']
    TinyOption: typeof import('@opentiny/vue')['Option']
    TinyProgress: typeof import('@opentiny/vue')['Progress']
    TinySelect: typeof import('@opentiny/vue')['Select']
    TinySubmenu: typeof import('@opentiny/vue')['Submenu']
    TinyTag: typeof import('@opentiny/vue')['Tag']
    TinyTreeMenu: typeof import('@opentiny/vue')['TreeMenu']
  }
}
