/**
 * @Author: weipc 755197142@qq.com
 * @Date: 2025-02-19 20:49:00
 * @LastEditors: weipc 755197142@qq.com
 * @LastEditTime: 2025-02-19 21:41:11
 * @FilePath: src/global/theme.ts
 * @Description: 这是默认设置,可以在设置》工具》File Description中进行配置
 */
const DefaultTheme = {
    id: 'tiny-default-theme',
    name: 'DefaultTheme',
    data: {
        'tv-base-color-brand': '#6366f1',
        'tv-base-color-brand-1': '#f7f7fe',
        'tv-base-color-brand-2': '#dadafc',
        'tv-base-color-brand-3': '#bcbdf9',
        'tv-base-color-brand-4': '#9ea0f6',
        'tv-base-color-brand-5': '#8183f4',
        'tv-base-color-brand-6': '#6366f1',
        'tv-base-color-brand-7': '#5457cd',
        'tv-base-color-brand-8': '#4547a9',
        'tv-base-color-brand-9': '#363885',
        'tv-base-color-brand-10': '#282960',
        'tv-base-color-brand-11': '#191a3c',
        'tv-base-color-brand-12': '#7fa6d4',
        'tv-base-color-brand-13': '#b6d4f2',

        'tv-base-color-common-1': '#ffffff',
        'tv-base-color-common-2': '#fafafa',
        'tv-base-color-common-3': '#f5f5f5',
        'tv-base-color-common-4': '#f0f0f0',
        'tv-base-color-common-5': '#e6e6e6',
        'tv-base-color-common-6': '#dbdbdb',
        'tv-base-color-common-7': '#c2c2c2',
        'tv-base-color-common-8': '#808080',
        'tv-base-color-common-9': '#595959',
        'tv-base-color-common-10': '#333333',
        'tv-base-color-common-11': '#191919',
        'tv-base-color-common-12': '#000000',

        'tv-base-color-success-1': '#ecfdf5',
        'tv-base-color-success-2': '#d1fae5',
        'tv-base-color-success-3': '#a7f3d0',
        'tv-base-color-success-4': '#6ee7b7',
        'tv-base-color-success-5': '#34d399',
        'tv-base-color-success-6': '#10b981',
        'tv-base-color-success-7': '#059669',
        'tv-base-color-success-8': '#047857',
        'tv-base-color-success-9': '#065f46',
        'tv-base-color-success-10': '#064e3b',
        'tv-base-color-success-11': '#022c22',
        'tv-base-color-success-12': '#a2c777',
        'tv-base-color-success-13': '#d2e6b8',
        'tv-base-color-success-14': '#e6f2d5',

        'tv-base-color-error-1': '#fef2f2',
        'tv-base-color-error-2': '#fee2e2',
        'tv-base-color-error-3': '#fecaca',
        'tv-base-color-error-4': '#fca5a5',
        'tv-base-color-error-5': '#f87171',
        'tv-base-color-error-6': '#ef4444',
        'tv-base-color-error-7': '#dc2626',
        'tv-base-color-error-8': '#b91c1c',
        'tv-base-color-error-9': '#991b1b',
        'tv-base-color-error-10': '#7f1d1d',
        'tv-base-color-error-11': '#450a0a',
        'tv-base-color-error-12': '#f2c5c2',
        'tv-base-color-error-13': '#fce3e1',

        'tv-base-color-warn-1': '#fffbeb',
        'tv-base-color-warn-2': '#fef3c7',
        'tv-base-color-warn-3': '#fde68a',
        'tv-base-color-warn-4': '#fcd34d',
        'tv-base-color-warn-5': '#fbbf24',
        'tv-base-color-warn-6': '#f59e0b',
        'tv-base-color-warn-7': '#d97706',
        'tv-base-color-warn-8': '#b45309',
        'tv-base-color-warn-9': '#92400e',
        'tv-base-color-warn-10': '#78350f',
        'tv-base-color-warn-11': '#451a03',
        'tv-base-color-warn-12': '#d6a981',
        'tv-base-color-warn-13': '#f2d8c2',
        'tv-base-color-warn-secondary-1': '#ffb700',

        'tv-base-color-info-1': '#f0f9ff',
        'tv-base-color-info-2': '#e0f2fe',
        'tv-base-color-info-3': '#bae6fd',
        'tv-base-color-info-4': '#7dd3fc',
        'tv-base-color-info-5': '#38bdf8',
        'tv-base-color-info-6': '#0ea5e9',
        'tv-base-color-info-7': '#0284c7',
        'tv-base-color-info-8': '#0369a1',
        'tv-base-color-info-9': '#075985',
        'tv-base-color-info-10': '#0c4a6e',
        'tv-base-color-info-11': '#082f49',
        'tv-base-color-info-12': '#7fa6d4',
        'tv-base-color-info-13': '#b6d4f2',

        'tv-color-success-text': 'var(--tv-base-color-success-6)',
        'tv-color-success-text-primary': 'var(--tv-base-color-common-11)',
        'tv-color-success-text-white': 'var(--tv-base-color-common-1)',
        'tv-color-success-bg': 'var(--tv-base-color-success-6)',
        'tv-color-success-bg-light': 'var(--tv-base-color-success-14)',
        'tv-color-success-bg-white': 'var(--tv-base-color-common-1)',
        'tv-color-success-border': 'var(--tv-base-color-success-6)',
        'tv-color-success-border-light': 'var(--tv-base-color-success-14)',
        'tv-color-success-icon': 'var(--tv-base-color-success-6)',

        'tv-color-error-text': 'var(--tv-base-color-error-6)',
        'tv-color-error-text-primary': 'var(--tv-base-color-common-11)',
        'tv-color-error-text-white': 'var(--tv-base-color-common-1)',
        'tv-color-error-bg': 'var(--tv-base-color-error-6)',
        'tv-color-error-bg-light': 'var(--tv-base-color-error-13)',
        'tv-color-error-bg-white': 'var(--tv-base-color-common-1)',
        'tv-color-error-border': 'var(--tv-base-color-error-6)',
        'tv-color-error-border-light': 'var(--tv-base-color-error-13)',
        'tv-color-error-icon': 'var(--tv-base-color-error-6)',

        'tv-color-warn-text': 'var(--tv-base-color-warn-6)',
        'tv-color-warn-text-primary': 'var(--tv-base-color-common-11)',
        'tv-color-warn-text-white': 'var(--tv-base-color-common-1)',
        'tv-color-warn-bg': 'var(--tv-base-color-warn-6)',
        'tv-color-warn-bg-light': 'var(--tv-base-color-warn-2)',
        'tv-color-warn-bg-white': 'var(--tv-base-color-common-1)',
        'tv-color-warn-border': 'var(--tv-base-color-warn-6)',
        'tv-color-warn-border-light': 'var(--tv-base-color-warn-2)',
        'tv-color-warn-icon': 'var(--tv-base-color-warn-6)',

        'tv-color-info-text': 'var(--tv-base-color-info-6)',
        'tv-color-info-text-primary': 'var(--tv-base-color-common-11)',
        'tv-color-info-text-white': 'var(--tv-base-color-common-1)',
        'tv-color-info-bg': 'var(--tv-base-color-info-6)',
        'tv-color-info-bg-light': 'var(--tv-base-color-info-2)',
        'tv-color-info-bg-white': 'var(--tv-base-color-common-1)',
        'tv-color-info-border': 'var(--tv-base-color-info-6)',
        'tv-color-info-border-light': 'var(--tv-base-color-info-2)',
        'tv-color-info-icon': 'var(--tv-base-color-info-6)',

        'tv-color-act-primary-text': 'var(--tv-base-color-brand)',
        'tv-color-act-primary-text-hover': 'var(--tv-base-color-brand)',
        'tv-color-act-primary-text-active': 'var(--tv-base-color-brand)',
        'tv-color-act-primary-text-inverse-tint': 'var(--tv-base-color-common-1)',
        'tv-color-act-primary-text-inverse-tint-hover': 'var(--tv-base-color-common-1)',
        'tv-color-act-primary-text-inverse-tint-active': 'var(--tv-base-color-common-1)',

        'tv-color-act-primary-bg': 'var(--tv-base-color-brand)',
        'tv-color-act-primary-bg-hover': 'var(--tv-base-color-common-9)',
        'tv-color-act-primary-bg-active': 'var(--tv-base-color-common-9)',

        'tv-color-act-primary-bg-white': 'var(--tv-base-color-common-1)',
        'tv-color-act-primary-bg-white-hover': 'var(--tv-base-color-common-1)',
        'tv-color-act-primary-bg-white-active': 'var(--tv-base-color-common-1)',

        'tv-color-act-primary-border': 'var(--tv-base-color-brand)',
        'tv-color-act-primary-border-hover': 'var(--tv-base-color-common-9)',
        'tv-color-act-primary-border-active': 'var(--tv-base-color-common-9)',

        'tv-color-act-primary-border-light': 'var(--tv-base-color-common-9)',
        'tv-color-act-primary-border-light-hover': 'var(--tv-base-color-common-1)',
        'tv-color-act-primary-border-light-active': 'var(--tv-base-color-common-1)',
        'tv-color-act-primary-border-light-hover-1': 'var(--tv-base-color-common-7)',
        'tv-color-act-primary-border-light-active-1': 'var(--tv-base-color-common-7)',

        'tv-color-act-primary-plain-text-hover': 'var(--tv-base-color-brand)',
        // More interaction colors can be added in similar fashion
    },
};

export { DefaultTheme };
